# Generated by /feature-spec
# Feature: ETag Generation and Validation
# Stack: generic
# Assumptions: 2 (see etag-generation-and-validation_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@etag-generation-and-validation
Feature: ETag Generation and Validation
  As a client of the User API
  I want the GET /users/{user_id} endpoint to return an ETag header
  So that I can perform conditional GET requests and avoid downloading unchanged data

  Background:
    Given the User API is running
    And a user exists with ID "user-123"
    And the user resource has a current state

  # Why: Core happy-path — validates that a standard GET returns an ETag
  # [ASSUMPTION: confidence=low] The ETag is a strong validator based on a hash of the resource body
  @key-example @smoke
  Scenario: A standard GET request returns an ETag header
    When I send a GET request for user "user-123"
    Then the request should succeed
    And the response should include an ETag header
    And the ETag should be a strong validator

  # Why: Core happy-path — validates that a matching If-None-Match returns 304 with no body
  # [ASSUMPTION: confidence=low] The If-None-Match header must match the ETag exactly
  @key-example
  Scenario: A GET request with a matching If-None-Match returns 304 with no body
    When I send a GET request for user "user-123" with an If-None-Match header matching the current ETag
    Then the request should return a Not Modified response
    And the response body should be empty

  # Why: Boundary — just-inside: ETag matches exactly
  @boundary
  Scenario: A GET request with an exact ETag match returns 304
    When I send a GET request for user "user-123" with an If-None-Match header matching the current ETag
    Then the request should return a Not Modified response
    And the response body should be empty

  # Why: Boundary — just-outside: ETag does not match (different value)
  @boundary @negative
  Scenario: A GET request with a non-matching If-None-Match returns the full resource
    When I send a GET request for user "user-123" with an If-None-Match header that does not match the current ETag
    Then the request should succeed
    And the response should include an ETag header
    And the response body should contain the user resource

  # Why: Negative — missing If-None-Match header should still return full resource
  @negative
  Scenario: A GET request without an If-None-Match header returns the full resource
    When I send a GET request for user "user-123" without an If-None-Match header
    Then the request should succeed
    And the response should include an ETag header
    And the response body should contain the user resource

  # Why: Negative — malformed If-None-Match header should be handled gracefully
  @negative
  Scenario: A GET request with a malformed If-None-Match header returns the full resource
    When I send a GET request for user "user-123" with a malformed If-None-Match header
    Then the request should succeed
    And the response should include an ETag header
    And the response body should contain the user resource

  # Why: Edge case — ETag changes between requests (resource updated)
  @edge-case
  Scenario: A GET request with a stale If-None-Match returns the updated resource
    Given the user resource has changed since the last request
    When I send a GET request for user "user-123" with an If-None-Match header matching the old ETag
    Then the request should succeed
    And the response should include a new ETag header
    And the response body should contain the updated user resource

  # Why: Edge case — concurrent requests with same ETag
  @edge-case
  Scenario: Concurrent GET requests with the same If-None-Match both return 304
    When two concurrent GET requests are sent for user "user-123" with the same If-None-Match header
    Then both requests should return a Not Modified response
    And both response bodies should be empty