# Generated by /feature-spec
# Feature: Add deleted_at column to users table
# Stack: generic
# Assumptions: 2 (see add-deleted-at-column-to-users-table_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@database-schema
Feature: Add deleted_at column to users table
  As a developer
  I want the users table to have a nullable deleted_at timestamp column
  So that the application can perform soft-delete operations and queries without failing on a missing column

  Background:
    Given the database schema is initialized
    And the users table exists without a deleted_at column

  # Why: Core happy-path — verifies the column exists and is nullable
  # [ASSUMPTION: confidence=low] The deleted_at column must be a nullable timestamp
  @key-example @smoke
  Scenario: The deleted_at column exists and is nullable
    When I apply the database migration to add the deleted_at column
    Then the users table should contain a deleted_at column
    And the deleted_at column should accept null values
    And the deleted_at column should be of timestamp type

  # Why: Boundary — just-inside: a row with a null deleted_at is valid
  # [ASSUMPTION: confidence=low] The database supports nullable timestamp columns
  @boundary
  Scenario: A user record can have a null deleted_at value
    Given a user record exists with a null deleted_at value
    When I query the user record
    Then the query should succeed
    And the deleted_at value should be null

  # Why: Boundary — just-outside: a non-null timestamp is also valid
  @boundary
  Scenario: A user record can have a non-null deleted_at value
    Given a user record exists with a non-null deleted_at timestamp
    When I query the user record
    Then the query should succeed
    And the deleted_at value should be a valid timestamp

  # Why: Negative — the column must not be required (non-nullable)
  @negative
  Scenario: The deleted_at column does not require a value
    When I attempt to create a user without specifying a deleted_at value
    Then the user creation should succeed
    And the deleted_at value should be recorded as null

  # Why: Negative — the column must not be a different type (e.g., boolean)
  @negative
  Scenario: The deleted_at column is not a boolean type
    When I attempt to set the deleted_at column to a boolean value
    Then the database should reject the operation
    And the error should indicate a type mismatch