# Generated by /feature-spec
# Feature: Daily User Creation Count
# Stack: generic
# Assumptions: 3 (see daily-user-creation-count_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@user-analytics
Feature: Daily User Creation Count
  As an analytics consumer
  I want to retrieve the number of users created on each of the last 7 days
  So that I can monitor user growth trends over a rolling week

  Background:
    Given the user creation service is running
    And the system records user creation timestamps

  # Why: Core happy-path — verifies the 7-day window and oldest-first ordering
  # [ASSUMPTION: confidence=low] The response includes exactly 7 data points, one for each of the last 7 days
  @key-example @smoke
  Scenario: A request for daily user creation counts returns exactly seven days ordered oldest first
    When I request the daily user creation counts
    Then the request should succeed
    And the response should contain exactly seven data points
    And the oldest day should be the first entry in the list
    And the most recent day should be the last entry in the list

  # Why: Boundary — exactly 7 days is the required window size
  @boundary
  Scenario: The response contains exactly seven days of data
    When I request the daily user creation counts
    Then the response should contain exactly seven data points

  # Why: Boundary — just outside the 7-day window (6 days) should not be returned
  @boundary @negative
  Scenario: The response does not include data older than seven days
    When I request the daily user creation counts
    Then the response should not contain any data older than seven days

  # Why: Negative — non-GET methods must be rejected
  @negative
  Scenario: A POST request to the endpoint is rejected
    When I send a POST request to the daily user creation counts endpoint
    Then the request should be rejected

  # Why: Negative — an empty dataset should still return seven days with zero counts
  @negative
  Scenario: The response returns zero counts for all days when no users were created
    Given no users were created in the last seven days
    When I request the daily user creation counts
    Then the request should succeed
    And each of the seven days should have a count of zero

  # Why: Edge case — partial data for the current day (incomplete day)
  # [ASSUMPTION: confidence=low] The current day is included in the 7-day window even if incomplete
  @edge-case
  Scenario: The response includes the current day even if it is incomplete
    Given the current day is included in the seven-day window
    When I request the daily user creation counts
    Then the response should include the current day
    And the current day should have a count reflecting users created so far today

  # Why: Edge case — response format is JSON (inferred from problem statement)
  # [ASSUMPTION: confidence=low] The response body is a JSON array of objects
  @edge-case
  Scenario: The response body is formatted as a JSON array
    When I request the daily user creation counts
    Then the response body should be a JSON array
    And each entry should contain a date and a count