# Generated by /feature-spec
# Feature: User Deletion API
# Stack: generic
# Assumptions: 3 (see user-deletion-api_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@user-management
Feature: User Deletion API
  As a system administrator or authorized service
  I want to delete a user by their unique identifier
  So that the user is permanently removed and no longer included in any user counts

  Background:
    Given the user management service is running
    And the user database contains a user with ID "user-123"
    And the total user count endpoint returns 10 users

  # Why: Core happy-path — verifies successful deletion returns 204 and removes the user
  # [ASSUMPTION: confidence=low] The user deletion is a hard delete rather than a soft delete.
  # [ASSUMPTION: confidence=low] The system currently has at least one count endpoint that returns the total number of users.
  @key-example @smoke
  Scenario: Deleting an existing user succeeds
    When I send a delete request for user "user-123"
    Then the request should succeed
    And the user "user-123" should no longer exist
    And the total user count should be 9

  # Why: Boundary — unknown ID should return 404
  @boundary @negative
  Scenario: Deleting a non-existent user returns not found
    When I send a delete request for user "non-existent-id"
    Then the request should not succeed
    And the response should indicate the user was not found

  # Why: Negative — deleting a user that was already deleted (idempotency check)
  @negative
  Scenario: Deleting an already deleted user returns not found
    Given the user "user-123" has already been deleted
    When I send a delete request for user "user-123"
    Then the request should not succeed
    And the response should indicate the user was not found

  # Why: Edge case — deletion is reflected in real time across all count endpoints
  # [ASSUMPTION: confidence=low] The count endpoints are expected to reflect deletions in near real-time.
  @edge-case
  Scenario: Deletion is reflected in real time across all count endpoints
    When I send a delete request for user "user-123"
    Then the request should succeed
    And the total user count should be 9
    And any other count endpoint should also reflect the reduced count