# Generated by /feature-spec
# Feature: User Domain Count API
# Stack: generic
# Assumptions: 3 (see get-users-count-by-domain_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@user-analytics
Feature: User Domain Count API
  As a data analyst or reporting service
  I want to retrieve the number of users grouped by their email domain
  So that I can understand the distribution of users across different domains

  Background:
    Given the user service is running
    And the user data store is available

  # Why: Core happy-path — verifies the primary function with data present
  # [ASSUMPTION: confidence=low] The endpoint returns a JSON array of objects with domain and count fields
  @key-example @smoke
  Scenario: A request returns domain counts ordered by count descending
    When I request the domain count endpoint
    Then the response should succeed
    And the response should contain a list of domain counts
    And each entry should include a domain string and a count
    And the entries should be ordered by count in descending order

  # Why: Boundary — empty user set should return an empty list, not an error
  @boundary
  Scenario: An empty user set returns an empty list
    Given there are no users in the system
    When I request the domain count endpoint
    Then the response should succeed
    And the response should contain an empty list

  # Why: Negative — endpoint should not accept unsupported HTTP methods
  @negative
  Scenario: A POST request to the endpoint is rejected
    When I send a POST request to the domain count endpoint
    Then the request should be rejected

  # Why: Negative — endpoint should not accept unsupported HTTP methods
  @negative
  Scenario: A PUT request to the endpoint is rejected
    When I send a PUT request to the domain count endpoint
    Then the request should be rejected

  # Why: Negative — endpoint should not accept unsupported HTTP methods
  @negative
  Scenario: A DELETE request to the endpoint is rejected
    When I send a DELETE request to the domain count endpoint
    Then the request should be rejected

  # Why: Edge case — large number of domains should not crash the service
  # [ASSUMPTION: confidence=low] The endpoint supports up to 1000 domains in a single response
  @edge-case
  Scenario: The endpoint handles a large number of domains
    Given there are 1000 distinct email domains in the system
    When I request the domain count endpoint
    Then the response should succeed
    And the response should contain all 1000 domains
    And the entries should be ordered by count in descending order

  # Why: Edge case — domain with no users should not appear in the list
  @edge-case
  Scenario: Domains with no users are excluded from the list
    Given there is a domain with no users
    When I request the domain count endpoint
    Then the response should succeed
    And the response should not contain the domain with no users

  # Why: Edge case — malformed email addresses should be handled gracefully
  # [ASSUMPTION: confidence=low] Malformed email addresses are ignored and do not cause errors
  @edge-case
  Scenario: Malformed email addresses are ignored
    Given there is a user with a malformed email address
    When I request the domain count endpoint
    Then the response should succeed
    And the malformed email should not appear in the domain counts