# Generated by /feature-spec
# Feature: Active Count Endpoint
# Stack: generic
# Assumptions: 2 (see active-count-endpoint_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@active-count-endpoint
Feature: Active Count Endpoint
  As a monitoring service or administrator
  I want to retrieve the current count of active and inactive users via a read-only endpoint
  So that I can monitor user activity and system health without querying the database directly

  Background:
    Given the user statistics service is running
    And the user data store contains users with active and inactive status flags

  # Why: Core happy-path — verifies the endpoint returns both counts as separate integers
  # [ASSUMPTION: confidence=low] The endpoint returns a JSON response with active_count and inactive_count fields
  @key-example @smoke
  Scenario: A request to the active count endpoint returns both counts
    When I send a GET request to the active count endpoint
    Then the request should succeed
    And the response should contain an active count field
    And the response should contain an inactive count field
    And both counts should be non-negative integers

  # Why: Boundary — zero users in the system
  # [ASSUMPTION: confidence=low] The endpoint returns 0 for both counts when no users exist
  @boundary
  Scenario: The endpoint returns zero for both counts when no users exist
    Given the user data store contains no users
    When I send a GET request to the active count endpoint
    Then the request should succeed
    And the active count should be 0
    And the inactive count should be 0

  # Why: Negative — endpoint must be read-only (GET)
  @negative
  Scenario: A POST request to the active count endpoint is rejected
    When I send a POST request to the active count endpoint
    Then the request should be rejected

  # Why: Negative — endpoint should not accept arbitrary paths
  @negative
  Scenario: A request to an invalid path on the user statistics service is rejected
    When I send a GET request to an invalid path on the user statistics service
    Then the request should be rejected