# Generated by /feature-spec
# Feature: User Domain Analytics and User Creation Extension
# Stack: generic
# Assumptions: 3 (see user-domain-analytics-and-user-creation-extension_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@user-domain-analytics-and-user-creation-extension
Feature: User Domain Analytics and User Creation Extension
  As a system administrator or analytics consumer
  I want to query user counts by email domain on both fresh and existing databases
  And I want to create new users on a fresh database without manual data entry
  So that I can verify system readiness and perform analytics without pre-seeding data

  Background:
    Given the user service is running
    And the database is initialized

  # Why: Core happy-path for fresh database — verifies the endpoint returns an empty list rather than failing
  # [ASSUMPTION: confidence=low] GET /users/count-by-domain returns an empty list when no users exist
  @key-example @smoke
  Scenario: Querying user domain counts on a fresh database returns an empty list
    When I request the user domain counts
    Then the request should succeed
    And the response should contain an empty list of domain counts

  # Why: Core happy-path for existing database — verifies backward compatibility
  @key-example
  Scenario: Querying user domain counts on an existing database returns counts for each domain
    Given the database contains users with email addresses in the "example.com" domain
    And the database contains users with email addresses in the "test.org" domain
    When I request the user domain counts
    Then the request should succeed
    And the response should list "example.com" with a count greater than zero
    And the response should list "test.org" with a count greater than zero

  # Why: Core happy-path for user creation — verifies POST works on fresh database
  # [ASSUMPTION: confidence=low] POST /users requires a valid email address in the request body
  @key-example
  Scenario: Creating a new user on a fresh database succeeds
    Given the database is freshly created and empty
    When I create a new user with a valid email address
    Then the user should be created successfully
    And the user should appear in the user list

  # Why: Boundary — empty response body on fresh database (just-inside)
  # [ASSUMPTION: confidence=low] The response body for an empty domain count is an empty JSON array
  @boundary
  Scenario: A fresh database returns an empty array for domain counts
    Given the database is freshly created and empty
    When I request the user domain counts
    Then the response body should be an empty array

  # Why: Boundary — response with exactly one domain (just-inside)
  @boundary
  Scenario: A database with exactly one domain returns a single count entry
    Given the database contains users with email addresses in the "single.com" domain
    When I request the user domain counts
    Then the response should contain exactly one domain entry
    And the entry should be for "single.com"

  # Why: Negative — POST /users with missing required fields
  @negative
  Scenario: Creating a user without a required field fails
    Given the database is freshly created and empty
    When I attempt to create a user with missing required information
    Then the request should be rejected
    And the response should indicate the missing information

  # Why: Negative — GET /users/count-by-domain with invalid query parameters
  @negative
  Scenario: Querying with an invalid domain filter returns an error
    When I request the user domain counts with an invalid filter
    Then the request should be rejected
    And the response should indicate an invalid filter

  # Why: Edge case — concurrent user creation on fresh database
  @edge-case
  Scenario: Concurrent user creation on a fresh database handles race conditions
    Given the database is freshly created and empty
    When two users attempt to create themselves simultaneously
    Then both users should be created successfully
    And the database should contain exactly two users

  # Why: Edge case — POST /users with duplicate email on fresh database
  @edge-case
  Scenario: Creating a user with a duplicate email on a fresh database fails
    Given the database is freshly created and empty
    And a user with email "duplicate@example.com" already exists
    When I attempt to create another user with the same email
    Then the request should be rejected
    And the response should indicate the email is already in use