# Generated by /feature-spec
# Feature: Deactivate User Endpoint
# Stack: generic
# Assumptions: 2 (see deactivate-user_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@deactivate-user
Feature: Deactivate User Endpoint
  As a system administrator or authorized user
  I want to deactivate a user account via a PATCH request
  So that the user can no longer access the system while preserving their record

  Background:
    Given the user service is running
    And the user storage layer is available

  # Why: Core happy-path — transitions an active user to inactive and returns the updated user
  # [ASSUMPTION: confidence=low] The returned user object includes the updated status field
  @key-example @smoke
  Scenario: Deactivating an active user succeeds
    Given a user with ID "user-123" who is currently active
    When I send a PATCH request to deactivate the user
    Then the request should succeed
    And the user's status should be inactive
    And the response should contain the updated user object

  # Why: Boundary — unknown user ID returns 404
  @boundary @negative
  Scenario: Deactivating a non-existent user returns not found
    Given no user exists with ID "non-existent-id"
    When I send a PATCH request to deactivate the user
    Then the request should indicate the user was not found

  # Why: Boundary — already inactive user returns 409
  @boundary @negative
  Scenario: Deactivating an already inactive user returns conflict
    Given a user with ID "user-456" who is already inactive
    When I send a PATCH request to deactivate the user
    Then the request should indicate the user is already inactive

  # Why: Edge case — concurrent deactivation requests
  # [ASSUMPTION: confidence=low] Concurrent requests to deactivate the same user are handled gracefully
  @edge-case
  Scenario: Concurrent deactivation requests for the same user are handled gracefully
    Given a user with ID "user-789" who is currently active
    When I send two concurrent PATCH requests to deactivate the same user
    Then one request should succeed
    And the other request should indicate the user is already inactive

  # Why: Edge case — deactivation when the user service is unavailable
  @edge-case
  Scenario: Deactivation fails gracefully when the user service is unavailable
    Given the user service is unavailable
    When I send a PATCH request to deactivate a user
    Then the request should fail with a service unavailable response