# Generated by /feature-spec
# Feature: User Summary Endpoint
# Stack: generic
# Assumptions: 3 (see user-summary-endpoint_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@user-summary
Feature: User Summary Endpoint
  As a client of the api_test service
  I want to retrieve a user's public record enriched with derived fields
  So that I can display user information without performing additional calculations

  Background:
    Given the user data store is available
    And the cache mechanism is available

  # Why: Core happy-path — retrieves public record with derived fields for a known user
  @key-example @smoke
  Scenario: A known user's summary is returned with derived fields
    Given a user exists with id "usr-123", creation date "2024-01-15", and active status true
    When I request the summary for user "usr-123"
    Then the request should succeed
    And the response should contain the user's public record
    And the response should include the number of days since the user was created
    And the response should include whether the user is currently active

  # Why: Unknown user IDs must always return not found, regardless of database state
  @negative
  Scenario: An unknown user ID returns not found
    Given no user exists with id "usr-999"
    When I request the summary for user "usr-999"
    Then the request should fail with not found
    And the response should indicate that the requested user does not exist

  # Why: Boundary — database unavailable with cached record present (fallback path)
  @boundary
  Scenario: Database unavailable but cached record exists returns summary from cache
    Given the user data store is unavailable
    And a cached record exists for user "usr-123"
    When I request the summary for user "usr-123"
    Then the request should succeed
    And the response should contain the user's public record from the cache
    And the response should include the number of days since the user was created
    And the response should include whether the user is currently active

  # Why: Boundary — database unavailable with no cached record (failure path naming DB)
  @boundary @negative
  Scenario: Database unavailable and no cached record fails naming the database
    Given the user data store is unavailable
    And no cached record exists for user "usr-123"
    When I request the summary for user "usr-123"
    Then the request should fail
    And the response should explicitly name the database as the cause of the failure

  # Why: Edge case — unknown user ID when database is unavailable still returns not found
  @edge-case
  Scenario: Unknown user ID with database unavailable still returns not found
    Given the user data store is unavailable
    And no user exists with id "usr-999"
    And no cached record exists for user "usr-999"
    When I request the summary for user "usr-999"
    Then the request should fail with not found
    And the response should indicate that the requested user does not exist

  # Why: Edge case — database unavailable, cached record exists but user ID is unknown (cache miss for non-existent user)
  @edge-case
  Scenario: Unknown user ID with cached record for different user returns not found
    Given the user data store is unavailable
    And a cached record exists for user "usr-123"
    And no user exists with id "usr-999"
    When I request the summary for user "usr-999"
    Then the request should fail with not found
    And the response should indicate that the requested user does not exist
