# Generated by /feature-spec
# Feature: User Creation Analytics - Daily Counts
# Stack: generic
# Assumptions: 2 (see created-per-day_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@user-analytics
Feature: User Creation Analytics - Daily Counts
  As a product analyst
  I want to see the number of users created on each of the last 7 days
  So that I can monitor user growth trends over the past week

  Background:
    Given the user creation service is running
    And the system records user creation timestamps in UTC

  # Why: Core happy-path — returns exactly 7 days of data ordered oldest first
  # [ASSUMPTION: confidence=low] The endpoint returns exactly 7 data points covering the most recent 7-day window
  @key-example @smoke
  Scenario: A request to the daily counts endpoint returns exactly 7 days of data ordered oldest first
    When I request the daily user creation counts
    Then the response should contain exactly 7 data points
    And the data points should be ordered from the oldest day to the newest day
    And each data point should include a date and a count of users created on that date

  # Why: Boundary — exactly 7 days (just-inside)
  @boundary
  Scenario: The endpoint returns exactly 7 days of data when the system has been running for at least 7 days
    Given the system has been running for at least 7 days
    When I request the daily user creation counts
    Then the response should contain exactly 7 data points
    And the data points should be ordered from the oldest day to the newest day

  # Why: Boundary — exactly 7 days (just-outside)
  @boundary
  Scenario: The endpoint returns exactly 7 days of data when the system has been running for more than 7 days
    Given the system has been running for more than 7 days
    When I request the daily user creation counts
    Then the response should contain exactly 7 data points
    And the data points should be ordered from the oldest day to the newest day

  # Why: Negative — endpoint is missing
  @negative
  Scenario: A request to a non-existent endpoint returns a failure
    When I request a non-existent endpoint
    Then the request should fail

  # Why: Negative — service is unavailable
  @negative
  Scenario: The endpoint returns a failure when the service is unavailable
    Given the user creation service is unavailable
    When I request the daily user creation counts
    Then the request should fail

  # Why: Edge case — system has been running for less than 7 days
  # [ASSUMPTION: confidence=low] If the system has been running for less than 7 days, the endpoint returns 7 data points with zero counts for missing days
  @edge-case
  Scenario: The endpoint returns 7 data points even when the system has been running for less than 7 days
    Given the system has been running for less than 7 days
    When I request the daily user creation counts
    Then the response should contain exactly 7 data points
    And the data points should be ordered from the oldest day to the newest day
    And days with no user creations should be reported with a count of zero