# Generated by /feature-spec
# Feature: User Creation Daily Counts
# Stack: generic
# Assumptions: 3 (see created-per-day_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@user-analytics
Feature: User Creation Daily Counts
  As a product analyst
  I want to retrieve the number of users created on each of the last 7 days
  So that I can monitor user growth trends over the past week

  Background:
    Given the user creation service is running
    And the system has recorded user creation timestamps for at least the last 7 days

  # Why: Core happy-path — verifies the endpoint returns exactly 7 data points in the correct order
  # [ASSUMPTION: confidence=low] The response includes exactly 7 data points covering the most recent 7-day window
  @key-example @smoke
  Scenario: A request to the endpoint returns exactly 7 days of data ordered oldest to newest
    When I request the user creation counts for the last 7 days
    Then the request should succeed
    And the response should contain exactly 7 data points
    And the data points should be ordered from the oldest day to the newest day

  # Why: Boundary — just-inside: exactly 7 days of data
  @boundary
  Scenario: The endpoint returns data for exactly 7 days when 7 days of history exist
    Given the system has recorded user creation timestamps for exactly 7 days
    When I request the user creation counts for the last 7 days
    Then the request should succeed
    And the response should contain exactly 7 data points

  # Why: Boundary — just-outside: 8 days of history should still return only the most recent 7
  @boundary
  Scenario: The endpoint returns only the most recent 7 days when more than 7 days of history exist
    Given the system has recorded user creation timestamps for 8 days
    When I request the user creation counts for the last 7 days
    Then the request should succeed
    And the response should contain exactly 7 data points
    And the oldest data point should be from 6 days ago

  # Why: Negative — invalid HTTP method (POST instead of GET)
  @negative
  Scenario: A POST request to the endpoint is rejected
    When I send a POST request to the user creation counts endpoint
    Then the request should be rejected

  # Why: Negative — endpoint does not exist
  @negative
  Scenario: A request to a non-existent path returns a not-found response
    When I request a non-existent path
    Then the request should be rejected

  # Why: Edge case — system has fewer than 7 days of history (e.g., newly deployed)
  # [ASSUMPTION: confidence=low] If fewer than 7 days of history exist, the endpoint returns 7 data points with zero counts for missing days
  @edge-case
  Scenario: The endpoint returns 7 data points with zero counts when fewer than 7 days of history exist
    Given the system has recorded user creation timestamps for only 3 days
    When I request the user creation counts for the last 7 days
    Then the request should succeed
    And the response should contain exactly 7 data points
    And the data points for the missing days should have a count of zero

  # Why: Edge case — concurrent requests return consistent data
  @edge-case
  Scenario: Concurrent requests to the endpoint return consistent data
    When I send two simultaneous requests to the user creation counts endpoint
    Then both requests should succeed
    And both responses should contain the same 7 data points

  # Why: Edge case — response format is JSON with date-count pairs
  # [ASSUMPTION: confidence=low] The response format is a JSON array of objects, each containing a date string and a count integer
  @key-example
  Scenario: The response format is a JSON array of date-count pairs
    When I request the user creation counts for the last 7 days
    Then the response should be a JSON array
    And each item in the array should contain a date and a count