# Generated by /feature-spec
# Feature: User Creation Analytics - Daily Counts
# Stack: generic
# Assumptions: 2 (see created-per-day_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@user-analytics
Feature: User Creation Analytics - Daily Counts
  As a product analyst
  I want to see the number of users created each day for the last week
  So that I can monitor user growth trends

  Background:
    Given the user creation data store is available
    And the system records a timestamp for every user creation event

  # Why: Core happy-path — returns exactly 7 days ordered oldest first
  # [ASSUMPTION: confidence=low] The response includes the current day as the most recent entry
  @key-example @smoke
  Scenario: A request for daily counts returns exactly seven days ordered oldest to newest
    When I request the daily user creation counts
    Then the response should succeed
    And the response should contain exactly seven data points
    And the data points should be ordered from oldest to newest
    And each data point should include a date and a count

  # Why: Boundary — exactly 7 days is the required window
  @boundary
  Scenario: The endpoint returns exactly seven days of data
    When I request the daily user creation counts
    Then the response should succeed
    And the response should contain exactly seven data points

  # Why: Boundary — 6 days is just outside the required window
  @boundary @negative
  Scenario: The endpoint does not return fewer than seven days of data
    Given the system has only recorded data for the last six days
    When I request the daily user creation counts
    Then the response should succeed
    And the response should still contain exactly seven data points

  # Why: Negative — non-GET methods should be rejected
  @negative
  Scenario: A POST request to the endpoint is rejected
    When I send a POST request to the daily user creation counts endpoint
    Then the request should be rejected
    And the response should indicate that only GET is supported

  # Why: Negative — empty data set should still return seven days with zero counts
  @negative
  Scenario: The endpoint returns seven days of zero counts when no users were created
    Given no users have been created in the last seven days
    When I request the daily user creation counts
    Then the response should succeed
    And each of the seven data points should have a count of zero

  # Why: Edge case — concurrency: two simultaneous requests should both succeed independently
  @edge-case
  Scenario: Two simultaneous requests both return the same seven-day window
    When I send two identical requests for daily user creation counts at the same time
    Then both requests should succeed
    And both responses should contain the same seven data points ordered oldest to newest

  # Why: Edge case — data integrity: partial data for the current day is handled gracefully
  @edge-case
  Scenario: The endpoint includes the current day even if it is incomplete
    Given the current day has only partially completed user creation data
    When I request the daily user creation counts
    Then the response should succeed
    And the most recent data point should represent the current day
    And the count for the current day should reflect only the users created so far