# Generated by /feature-spec
# Feature: User Domain Discovery
# Stack: generic
# Assumptions: 2 (see user-domain-discovery_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@user-domain-discovery
Feature: User Domain Discovery
  As a system administrator or analyst
  I want to retrieve a sorted list of all unique email domains used by registered users
  So that I can understand the distribution of user domains and perform analytics

  Background:
    Given the user data store is accessible
    And the system contains registered users with email addresses

  # Why: Core happy-path — returns distinct domains in alphabetical order
  # [ASSUMPTION: confidence=low] The endpoint returns a JSON array of strings
  @key-example @smoke
  Scenario: A request to the domains endpoint returns a sorted list of unique domains
    When I request the list of user domains
    Then the request should succeed
    And the response should contain a list of distinct domains
    And the domains should be sorted alphabetically

  # Why: Boundary — empty domain list (no users)
  # [ASSUMPTION: confidence=low] An empty domain list returns an empty array rather than a 404
  @boundary
  Scenario: The domains endpoint returns an empty list when no users exist
    Given there are no registered users in the system
    When I request the list of user domains
    Then the request should succeed
    And the response should contain an empty list

  # Why: Negative — malformed email addresses should not produce invalid domains
  @negative
  Scenario: Malformed email addresses are excluded from the domain list
    Given a user with a malformed email address that has no domain part
    When I request the list of user domains
    Then the request should succeed
    And the malformed email should not result in an entry in the domain list

  # Why: Edge case — concurrency (two simultaneous requests)
  # [ASSUMPTION: confidence=low] The endpoint handles concurrent requests without error
  @edge-case
  Scenario: Concurrent requests to the domains endpoint both succeed
    When two requests for the domains are received simultaneously
    Then both requests should succeed
    And both should return the same list of domains