# Generated by /feature-spec
# Feature: Recent Users Endpoint
# Stack: generic
# Assumptions: 3 (see recent-users_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@user-listing
Feature: Recent Users Endpoint
  As a consumer of the user listing service
  I want to retrieve the most recently added users in newest-first order
  So that I can see who joined the system recently

  Background:
    Given the user store is available

  # Why: Core happy path — default limit returns newest users
  @key-example @smoke
  Scenario: Requesting recent users without a limit returns the default number of newest users
    Given there are users in the store with various creation timestamps
    When I request the recent users endpoint
    Then the response should succeed
    And the response should contain a list of user objects
    And the users should be ordered with the newest first
    And the list should contain the default number of users

  # Why: Explicit limit within valid range returns exactly that many
  @key-example
  Scenario: Requesting recent users with a valid explicit limit returns that many newest users
    Given there are users in the store with various creation timestamps
    When I request the recent users endpoint with a limit of 5
    Then the response should succeed
    And the response should contain a list of user objects
    And the users should be ordered with the newest first
    And the list should contain exactly 5 user objects

  # Why: Boundary — just inside the maximum allowed limit
  # [ASSUMPTION: confidence=low] Maximum allowed limit is 100 users
  @boundary
  Scenario: Requesting recent users at the maximum allowed limit returns that many users
    Given there are at least 100 users in the store with various creation timestamps
    When I request the recent users endpoint with a limit of 100
    Then the response should succeed
    And the response should contain a list of user objects
    And the users should be ordered with the newest first
    And the list should contain exactly 100 user objects

  # Why: Boundary — just outside the maximum allowed limit should be rejected
  # [ASSUMPTION: confidence=low] Maximum allowed limit is 100 users
  @boundary @negative
  Scenario: Requesting recent users with a limit exceeding the maximum is rejected
    Given there are users in the store with various creation timestamps
    When I request the recent users endpoint with a limit of 101
    Then the request should be rejected
    And the error should indicate the limit exceeds the maximum allowed

  # Why: Boundary — just inside the minimum valid limit (1)
  @boundary
  Scenario: Requesting recent users with a limit of 1 returns a single newest user
    Given there is at least one user in the store
    When I request the recent users endpoint with a limit of 1
    Then the response should succeed
    And the response should contain a list with exactly one user object
    And the user should be the newest in the store

  # Why: Boundary — zero is not a valid limit
  @boundary @negative
  Scenario: Requesting recent users with a limit of zero is rejected
    Given there are users in the store with various creation timestamps
    When I request the recent users endpoint with a limit of 0
    Then the request should be rejected
    And the error should indicate the limit must be positive

  # Why: Negative limits are invalid
  @negative
  Scenario: Requesting recent users with a negative limit is rejected
    Given there are users in the store with various creation timestamps
    When I request the recent users endpoint with a limit of -1
    Then the request should be rejected
    And the error should indicate the limit must be positive

  # Why: Non-integer limits are invalid
  @negative
  Scenario: Requesting recent users with a non-integer limit is rejected
    Given there are users in the store with various creation timestamps
    When I request the recent users endpoint with a limit of 5.5
    Then the request should be rejected
    And the error should indicate the limit must be an integer

  # Why: Empty store returns empty array, not error
  @key-example
  Scenario: Requesting recent users from an empty store returns an empty list
    Given the user store contains no users
    When I request the recent users endpoint
    Then the response should succeed
    And the response should contain an empty list of users
