# Generated by /feature-spec
# Feature: Normalize In-Memory SQLite URL
# Stack: generic
# Assumptions: 1 (see normalize-in-memory-sqlite-url_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@database-infrastructure
Feature: Normalize In-Memory SQLite URL
  As a developer running tests
  I want the in-memory SQLite database URL to be normalized
  So that tests pass consistently across SQLAlchemy 2.0 and 2.1 without pinning versions

  Background:
    Given the test harness is configured to use an in-memory SQLite database

  # Why: Core requirement — ensure the URL is compatible with SQLAlchemy 2.1's encoded format
  # [ASSUMPTION: confidence=low] The failure is caused by the change in how SQLAlchemy 2.1 encodes the in-memory SQLite URL
  @key-example @smoke
  Scenario: The generated in-memory URL uses the encoded format required by SQLAlchemy 2.1
    Given SQLAlchemy version 2.1 is active
    When the test harness requests the in-memory database URL
    Then the returned URL should be "sqlite+aiosqlite:///%3Amemory%3A"

  # Why: Just-inside boundary — ensure SQLAlchemy 2.0 still works with the normalized URL
  # [ASSUMPTION: confidence=low] The normalization logic must support both SQLAlchemy 2.0 and 2.1 simultaneously
  @boundary
  Scenario: The normalized URL remains compatible with SQLAlchemy 2.0
    Given SQLAlchemy version 2.0 is active
    When the test harness requests the in-memory database URL
    Then the returned URL should be compatible with SQLAlchemy 2.0

  # Why: Just-outside boundary — ensure the URL is not incorrectly decoded back to the legacy format
  # [ASSUMPTION: confidence=low] The legacy format 'sqlite:///:memory:' is no longer acceptable for SQLAlchemy 2.1
  @boundary @negative
  Scenario: The URL is not returned in the legacy unencoded format
    Given SQLAlchemy version 2.1 is active
    When the test harness requests the in-memory database URL
    Then the returned URL should not be "sqlite:///:memory:"

  # Why: Verify that the normalization logic does not accidentally affect non-in-memory URLs
  # [ASSUMPTION: confidence=low] The normalization logic only targets in-memory SQLite URLs
  @negative
  Scenario: Normalization does not affect standard file-based SQLite URLs
    Given a standard file-based SQLite URL "sqlite:///test.db"
    When the URL normalization logic is applied
    Then the returned URL should remain "sqlite:///test.db"

  # Why: Ensure the fix works when no database URL is explicitly provided (the failure case)
  # [ASSUMPTION: confidence=low] The test harness defaults to in-memory SQLite when no URL is provided
  @edge-case
  Scenario: No database URL is set in the environment
    Given no database URL is configured in the environment
    When the test harness requests the in-memory database URL
    Then the returned URL should be the normalized in-memory URL "sqlite+aiosqlite:///%3Amemory%3A"
