# Generated by /feature-spec
# Feature: Add min_count query parameter to GET /users/count-by-domain
# Stack: generic
# Assumptions: 2 (see add-min-count-query-parameter-to-get-users-count-by-domain_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@user-analytics-api
Feature: Add min_count query parameter to GET /users/count-by-domain
  As an analyst
  I want to filter the domain count list by a minimum user count
  So that I can quickly identify high-density domains without manual filtering

  Background:
    Given the user analytics service is running
    And the domain count endpoint is registered

  # Why: Core happy-path — verifies the optional parameter works as expected
  # [ASSUMPTION: confidence=low] The endpoint returns a JSON object mapping domain names to user counts
  @key-example @smoke
  Scenario: Providing a valid min_count filters domains below that count
    When I request the domain counts with a minimum count of 10
    Then the response should include only domains with 10 or more users
    And the response should not include any domains with fewer than 10 users

  # Why: Backward compatibility — omitting the parameter should return all domains
  @key-example
  Scenario: Omitting the min_count parameter returns all domains
    When I request the domain counts without a minimum count
    Then the response should include all domains regardless of user count

  # Why: Boundary — just-inside the minimum allowed value (0)
  @boundary
  Scenario: A minimum count of zero includes all domains
    When I request the domain counts with a minimum count of 0
    Then the response should include all domains

  # Why: Boundary — just-outside the minimum allowed value (negative)
  # [ASSUMPTION: confidence=low] Negative min_count values are rejected with a bad request response
  @boundary @negative
  Scenario: A negative minimum count is rejected
    When I request the domain counts with a minimum count of -1
    Then the request should be rejected with a bad request error

  # Why: Boundary — just-outside the maximum allowable value (if a limit exists)
  # [ASSUMPTION: confidence=low] The maximum allowable min_count is 10,000
  @boundary @negative
  Scenario: A minimum count exceeding the maximum allowed value is rejected
    When I request the domain counts with a minimum count of 10001
    Then the request should be rejected with a bad request error

  # Why: Negative — non-integer values should be rejected
  @negative
  Scenario: A non-integer minimum count is rejected
    When I request the domain counts with a minimum count of "abc"
    Then the request should be rejected with a bad request error

  # Why: Negative — empty string value for min_count
  @negative
  Scenario: An empty minimum count value is rejected
    When I request the domain counts with an empty minimum count
    Then the request should be rejected with a bad request error

  # Why: Edge case — very large valid min_count that exceeds any possible domain count
  @edge-case
  Scenario: A minimum count higher than any existing domain count returns no domains
    When I request the domain counts with a minimum count of 1000000
    Then the response should contain no domains