# Generated by /feature-spec
# Feature: Today's User Count Endpoint
# Stack: generic
# Assumptions: 4 (see todays-user-count_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@todays-user-count
Feature: Today's User Count Endpoint
  As a service operator or automated monitor
  I want to request the total number of users created today
  So that I can track daily user acquisition and system health

  Background:
    Given the api_test service is available
    And the user data store is accessible
    And the server timezone is configured to UTC

  # Why: Core happy-path — returns count for a typical day with users
  @key-example @smoke
  Scenario: Requesting today's user count returns the correct total
    Given there are 42 users in the data store created today
    And there are 15 users in the data store created on previous days
    When I request the count of users created today
    Then the response should contain a count of 42

  # Why: Boundary — zero users created today (empty set)
  @boundary @key-example
  Scenario: Requesting today's user count when no users were created today returns zero
    Given there are no users in the data store created today
    And there are 10 users in the data store created on previous days
    When I request the count of users created today
    Then the response should contain a count of 0

  # Why: Boundary — all users created today (maximal set)
  @boundary @key-example
  Scenario: Requesting today's user count when all users were created today returns the total
    Given there are 100 users in the data store created today
    And there are no users in the data store created on previous days
    When I request the count of users created today
    Then the response should contain a count of 100

  # Why: Boundary — users created at the exact start of today (just-inside)
  @boundary
  Scenario: Users created at the very start of today are included in the count
    # [ASSUMPTION: confidence=low] "Today" is defined as the interval from 00:00:00.000 UTC to 23:59:59.999 UTC inclusive
    Given there is one user created exactly at the start of today in UTC
    When I request the count of users created today
    Then the response should contain a count of 1

  # Why: Boundary — users created at the exact start of yesterday (just-outside)
  @boundary @negative
  Scenario: Users created at the very end of yesterday are not included in the count
    # [ASSUMPTION: confidence=low] "Today" is defined as the interval from 00:00:00.000 UTC to 23:59:59.999 UTC inclusive
    Given there is one user created exactly at the end of yesterday in UTC
    When I request the count of users created today
    Then the response should contain a count of 0

  # Why: Negative — database connectivity failure
  @negative @edge-case
  Scenario: Requesting the count fails gracefully when the data store is unavailable
    # [ASSUMPTION: confidence=low] The endpoint returns HTTP 503 Service Unavailable when the data store is unreachable
    When the user data store is unavailable
    And I request the count of users created today
    Then the request should fail with a service unavailable indication

  # Why: Negative — malformed or missing request
  @negative
  Scenario: Requesting the count with an invalid request format is rejected
    # [ASSUMPTION: confidence=low] The endpoint expects a well-formed HTTP GET request; any malformed request is rejected with a 400-level status
    When I send a malformed request to the count endpoint
    Then the request should be rejected as invalid

  # Why: Edge case — timezone boundary crossing
  @edge-case
  Scenario: Users created just before midnight UTC are counted correctly relative to the server timezone
    # [ASSUMPTION: confidence=low] The server timezone is UTC and "today" is strictly the current UTC calendar day
    Given there is one user created one second before midnight UTC
    And the server timezone is UTC
    When I request the count of users created today
    Then the response should contain a count of 0
