# Generated by /feature-spec
# Feature: Version Endpoint
# Stack: generic
# Assumptions: 1 (see version-endpoint_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@system-metadata
Feature: Version Endpoint
  As a
    service operator or automated monitoring tool
  I want to
    query a `/version` endpoint to retrieve the application version and build commit hash
  So that
    I can verify the identity of the deployed binary

  Background:
    Given the application is running
    And the build metadata (version string and git commit hash) has been injected into the application at startup

  # Why: Core happy-path — verifies the endpoint returns both required fields in JSON
  @key-example @smoke
  Scenario: The version endpoint returns the running build
    When I request the version endpoint
    Then the response should succeed
    And the response should be a JSON object
    And the response should contain an application version field
    And the response should contain a git commit hash field

  # Why: Boundary / negative — verifies that requesting an unsupported media type is refused
  @boundary @negative
  Scenario: The version endpoint rejects an unsupported media type
    When I request the version endpoint with an unsupported format
    Then the request should be refused
    And the response should indicate the format is not supported
