# Generated by /feature-spec
# Feature: User Creation Analytics - Created Per Day
# Stack: generic
# Assumptions: 3 (see user-creation-analytics/created-per-day_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@user-creation-analytics
Feature: User Creation Analytics - Created Per Day
  As an operations analyst
  I want to see the number of users created each day for the last week
  So that I can monitor user growth trends and detect anomalies

  Background:
    Given the user creation service is running
    And the users table contains historical creation data

  # Why: Core happy-path — verifies the 7-day window, ordering, and soft-deleted inclusion
  # [ASSUMPTION: confidence=low] The response includes exactly 7 entries, one for each of the last 7 days, ordered oldest to newest
  # [ASSUMPTION: confidence=low] The response format is a JSON array of objects with "date" (ISO-8601) and "count" (integer) keys
  # [ASSUMPTION: confidence=low] The count includes soft-deleted users
  @key-example @smoke
  Scenario: A successful request returns the last 7 days of creation counts
    When I request the user creation counts for the last 7 days
    Then the request should succeed
    And the response should contain exactly 7 entries
    And each entry should have a date and a count
    And the entries should be ordered from oldest to newest
    And the counts should include soft-deleted users

  # Why: Boundary — exactly 7 days (today + 6 preceding)
  # [ASSUMPTION: confidence=low] The 7-day window is inclusive of today and the 6 preceding days
  @boundary
  Scenario: The response includes exactly the last 7 days including today
    When I request the user creation counts for the last 7 days
    Then the response should include today's date
    And the response should include the date from 6 days ago
    And the response should not include the date from 7 days ago

  # Why: Negative — no users created in the window
  @negative
  Scenario: No users created in the last 7 days returns zero counts for each day
    Given no users were created in the last 7 days
    When I request the user creation counts for the last 7 days
    Then the request should succeed
    And each of the 7 entries should have a count of zero

  # Why: Edge case — all users in the window are soft-deleted
  # [ASSUMPTION: confidence=low] Soft-deleted users are indistinguishable from active users in the count
  @edge-case
  Scenario: All users created in the last 7 days are soft-deleted
    Given all users created in the last 7 days are soft-deleted
    When I request the user creation counts for the last 7 days
    Then the request should succeed
    And the counts should reflect the soft-deleted users