# Generated by /feature-spec
# Feature: Get User by ID Endpoint
# Stack: generic
# Assumptions: 3 (see get-user-by-id_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@user-management
Feature: Get User by ID Endpoint
  As a client of the User API
  I want to retrieve a single user by their unique identifier
  So that I can obtain the details of a specific user

  Background:
    Given the user service is running
    And the user repository contains a user with ID "user-123"

  # Why: Core happy-path — verifies that a valid ID returns the expected user
  # [ASSUMPTION: confidence=low] The response body includes a full user profile with id, name, and email
  @key-example @smoke
  Scenario: A valid user ID returns the user details
    When I request the user with ID "user-123"
    Then the request should succeed
    And the response should contain the user details for "user-123"

  # Why: Boundary — just-inside: ID exists
  @boundary
  Scenario: A user ID that exists returns the user
    When I request the user with ID "user-123"
    Then the request should succeed
    And the response should contain the user details for "user-123"

  # Why: Boundary — just-outside: ID does not exist
  # [ASSUMPTION: confidence=low] The 404 error response includes a JSON body with an error message field
  @boundary @negative
  Scenario: A user ID that does not exist returns a not found response
    When I request the user with ID "non-existent-id"
    Then the request should fail with a not found error
    And the error message should indicate the user was not found

  # Why: Negative — invalid ID format (e.g., empty)
  # [ASSUMPTION: confidence=low] The API validates that the ID segment is non-empty before querying
  @negative
  Scenario: An empty user ID returns a bad request error
    When I request the user with an empty ID
    Then the request should fail with a bad request error

  # Why: Negative — ID with special characters that are not valid identifiers
  @negative
  Scenario: A user ID containing special characters is rejected
    When I request the user with ID "user!@#"
    Then the request should fail with a bad request error

  # Why: Edge case — concurrent requests for the same user
  @edge-case
  Scenario: Multiple concurrent requests for the same user all succeed
    When I send multiple simultaneous requests for user "user-123"
    Then each request should succeed
    And each response should contain the same user details for "user-123"

  # Why: Edge case — user ID that is valid format but not in the system
  @edge-case
  Scenario: A validly formatted ID that is not present returns not found
    When I request the user with ID "user-999"
    Then the request should fail with a not found error
    And the error message should indicate the user was not found