# Generated by /feature-spec
# Feature: Get Users Created Per Day
# Stack: generic
# Assumptions: 3 (see get-users-created-per-day_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@user-analytics
Feature: Get Users Created Per Day
  As an analytics consumer
  I want to retrieve the number of users created on each of the last 7 days
  So that I can monitor user growth trends over the past week

  Background:
    Given the user creation service is running
    And the system records a creation timestamp for every user registration

  # Why: Core happy-path — returns exactly 7 days ordered oldest first
  # [ASSUMPTION: confidence=low] The response includes exactly 7 data points covering the most recent 7-day window
  @key-example @smoke
  Scenario: A successful request returns exactly seven days of data ordered oldest first
    When I request the user creation statistics for the last 7 days
    Then the request should succeed
    And the response should contain exactly seven data points
    And the data points should be ordered from the oldest day to the newest day

  # Why: Boundary — exactly 7 days is the required count
  @boundary
  Scenario: The response contains exactly seven data points
    When I request the user creation statistics for the last 7 days
    Then the response should contain exactly seven data points

  # Why: Boundary — 6 days would be insufficient
  @boundary @negative
  Scenario: The response does not contain fewer than seven data points
    When I request the user creation statistics for the last 7 days
    Then the response should not contain fewer than seven data points

  # Why: Negative — non-GET methods must be rejected
  @negative
  Scenario: A POST request to the endpoint is rejected
    When I send a POST request to the user creation statistics endpoint
    Then the request should be rejected

  # Why: Negative — missing authentication should be rejected
  # [ASSUMPTION: confidence=low] The endpoint requires authentication
  @negative
  Scenario: An unauthenticated request is rejected
    When I request the user creation statistics without authentication
    Then the request should be rejected

  # Why: Edge case — days with no new users should still be reported
  # [ASSUMPTION: confidence=low] Days with no new users are reported with a count of zero
  @edge-case
  Scenario: Days with no new users are reported with a count of zero
    Given there were no new users created on a day within the last week
    When I request the user creation statistics for the last 7 days
    Then the response should include that day with a count of zero

  # Why: Edge case — the oldest day in the 7-day window is exactly 6 days ago
  @boundary
  Scenario: The oldest day in the response is exactly six days before today
    When I request the user creation statistics for the last 7 days
    Then the oldest day in the response should be exactly six days before today

  # Why: Edge case — the newest day in the 7-day window is today
  @boundary
  Scenario: The newest day in the response is today
    When I request the user creation statistics for the last 7 days
    Then the newest day in the response should be today