# Generated by /feature-spec
# Feature: User Creation Daily Counts
# Stack: generic
# Assumptions: 3 (see get-users-created-per-day_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@user-analytics
Feature: User Creation Daily Counts
  As a product manager or analyst
  I want to see the number of users created on each of the last 7 days
  So that I can monitor user acquisition trends over the past week

  Background:
    Given the user creation service is running
    And the user database contains records for the last 7 days

  # Why: Core happy-path — verifies the endpoint returns exactly 7 data points in the correct order
  # [ASSUMPTION: confidence=low] The response includes exactly 7 data points for the last 7 days
  @key-example @smoke
  Scenario: Requesting the daily user counts returns exactly seven days of data ordered oldest first
    When I request the daily user counts for the last week
    Then the response should succeed
    And the response should contain exactly seven data points
    And the data points should be ordered from the oldest day to the most recent day

  # Why: Boundary — verifies the oldest day in the 7-day window is included
  # [ASSUMPTION: confidence=low] The 7-day window is inclusive of the oldest day
  @boundary
  Scenario: The oldest day in the 7-day window is included in the response
    Given the user database has records for exactly 7 days
    When I request the daily user counts for the last week
    Then the response should succeed
    And the response should include data for the oldest day in the window

  # Why: Boundary — verifies the most recent day is included
  @boundary
  Scenario: The most recent day is included in the response
    Given the user database has records for the last 7 days including today
    When I request the daily user counts for the last week
    Then the response should succeed
    And the response should include data for the most recent day

  # Why: Negative — verifies the endpoint rejects non-GET methods
  @negative
  Scenario: The endpoint rejects non-GET requests
    When I send a POST request to the daily user counts endpoint
    Then the request should be rejected
    And the response should indicate that only GET is allowed

  # Why: Negative — verifies the endpoint rejects requests without authentication
  # [ASSUMPTION: confidence=low] The endpoint requires authentication
  @negative
  Scenario: The endpoint rejects unauthenticated requests
    When I request the daily user counts without authentication
    Then the request should be rejected
    And the response should indicate that authentication is required

  # Why: Edge case — verifies behaviour when no users were created in the last 7 days
  @edge-case
  Scenario: The endpoint returns zero counts when no users were created in the last 7 days
    Given no users were created in the last 7 days
    When I request the daily user counts for the last week
    Then the response should succeed
    And each of the seven data points should show a count of zero

  # Why: Edge case — verifies behaviour when the database is unavailable
  @edge-case
  Scenario: The endpoint fails gracefully when the user database is unavailable
    Given the user database is unavailable
    When I request the daily user counts for the last week
    Then the request should fail
    And the response should indicate that the service is temporarily unavailable