# Generated by /feature-spec
# Feature: Get Users Created Per Day
# Stack: generic
# Assumptions: 3 (see get-users-created-per-day_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@user-analytics
Feature: Get Users Created Per Day
  As a consumer of the User Analytics API
  I want to retrieve the number of users created on each of the last 7 days
  So that I can observe recent registration trends

  Background:
    Given the user service is running
    And the user table contains creation timestamps for all users

  # Why: Core happy-path — verifies the exact count and ordering contract
  # [ASSUMPTION: confidence=low] The response includes exactly 7 data points for the preceding week
  @key-example @smoke
  Scenario: A request to the endpoint returns exactly seven days of data ordered oldest first
    When I send a GET request to the users created per day endpoint
    Then the request should succeed
    And the response should contain exactly seven data points
    And the data points should be ordered from the oldest day to the newest day

  # Why: Boundary — verifies the oldest day is exactly 7 days ago (just inside)
  # [ASSUMPTION: confidence=low] The oldest day in the response is exactly 7 days before the current day
  @boundary
  Scenario: The oldest day in the response is exactly seven days ago
    Given today is 2026-07-09
    When I send a GET request to the users created per day endpoint
    Then the oldest day in the response should be 2026-07-02

  # Why: Boundary — verifies the newest day is yesterday (just outside today)
  # [ASSUMPTION: confidence=low] The newest day in the response is yesterday, not today
  @boundary
  Scenario: The newest day in the response is yesterday
    Given today is 2026-07-09
    When I send a GET request to the users created per day endpoint
    Then the newest day in the response should be 2026-07-08

  # Why: Negative — verifies the endpoint rejects non-GET methods
  @negative
  Scenario: A POST request to the endpoint is rejected
    When I send a POST request to the users created per day endpoint
    Then the request should be rejected

  # Why: Negative — verifies the endpoint rejects requests without authentication
  # [ASSUMPTION: confidence=low] The endpoint requires authentication
  @negative
  Scenario: A request without authentication is rejected
    When I send a GET request to the users created per day endpoint without authentication
    Then the request should be rejected

  # Why: Edge case — verifies behavior when no users have been created in the last 7 days
  @edge-case
  Scenario: The endpoint returns zero counts for all days when no users were created
    Given no users were created in the last seven days
    When I send a GET request to the users created per day endpoint
    Then the request should succeed
    And every day in the response should have a count of zero

  # Why: Edge case — verifies behavior when the user table is empty
  @edge-case
  Scenario: The endpoint returns zero counts for all days when the user table is empty
    Given the user table is empty
    When I send a GET request to the users created per day endpoint
    Then the request should succeed
    And every day in the response should have a count of zero